### ISSUE TITLE
Issues in the submitted 12.0.0 packages

### ISSUE THREAD

**Issue by boris-kolpackov** [b8u/build2-package-strong_type#1]
I am reviewing the submitted packages and noted the following issues:

1. Could you please transfer this repository to the https://github.com/build2-packaging/ organization (calling it just `strong_type`). I've send you (b8u) an invite. You will still be the owner of the repository, we just want some continuity in case people loose interest, etc., and so now requite all third-party packages that are published to cppget.org to be under the build2-packaging organization.

   Note that you will also want to update `package-url` value in the `manifest` files.

2. The `manifest` `summary` value is quite poor in both packages, for guidelines, see: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-forget-update-manifest

3. You don't need `depends: strong_type == $` in tests, this dependency is implied by `tests: strong_type-tests == $`.

4. `tests/: install = false`: you don't have `tests/`.

5. I would add the `LICENSE` file to the `-tests` package since it includes upstream code.

6. The `-tests` package depends on `fmt` but this library is not imported anywhere AFAICS.

I think 5 and 6 warrant a revision before this can be migrated to public.

**Comment by b8u** [comment]
Thank you for the feedback!

1. done
2. changed to a summary line from the official repo (also for tests)
3. removed
4. removed
5. symlined
6. added fmt10 tests. There are fmt9 and fmt8 in upstream, but don't think it's necessarily in case of packaging.

**Comment by boris-kolpackov** [comment]
Thanks, that looks good.

The only issue I see is the missing `legal{LICENSE}` prerequisite in `strong_type-tests/build2file` (similar to `strong_type/build2file`).

Once this is fixed, could you release a revision (`bdep release --revision`) and then publish it (`bdep publish`)? Thanks!

**Comment by b8u** [comment]
I added the `legal` prerequisite and tried to published, but I have an error:

```
$ bdep publish
publishing:
  to:      https://cppget.org
  as:      b8u <lily.coder@gmail.com>

  package: strong_type
  version: 12.0.0+1
  project: strong_type
  section: stable
  control: https://github.com/build2-packaging/strong_type.git

  package: strong_type-tests
  version: 12.0.0+1
  project: strong_type
  section: stable
  control: https://github.com/build2-packaging/strong_type.git
continue? [y/n] y
pushing branch build2-control
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 363 bytes | 363.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
submitting strong_type-12.0.0+1.tar.gz
############################################################################################################################################################################################################ 100.0%
error: project owner authentication failed
  info: reference: 543d28eac490
```

probably the error occurs because I transferred the repo to build2-packaging

**Comment by boris-kolpackov** [comment]
> probably the error occurs because I transferred the repo to build2-packaging

Yes, I've now adjusted the ownership information, please try again.

**Comment by boris-kolpackov** [comment]
Published, thanks!
